[tool.poetry]
name = "atlantisbot"
version = "0.1.0"
description = ""
authors = ["johnvictorfs <johnvictorfs@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
"discord.py" = "^1.0"
rs3clans = "^1.1"
beautifulsoup4 = "^4.7"
colorama = "^0.4.1"
sqlalchemy = "^1.3"
pandas = "^0.24.2"
matplotlib = "^3.0"
lxml = "^4.3"
alembic = "^1.0"
psycopg2-binary = "^2.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
