[tool.poetry]
name = "atlantis-bot"
version = "0.1.0"
description = ""
authors = ["John Victor <johnvictorfs@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
"discord.py" = {git = "https://github.com/Rapptz/discord.py", branch = "rewrite"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
